In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import fsolve
from math import factorial as fc

%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

### 6.1

In [19]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
X = np.linalg.solve(A, B)
print(X)

[-9.2         0.9         6.46666667]


In [27]:
A1 = np.linalg.inv(A)
print(A1)
print(f'det = {np.linalg.det(A)}')

X = np.dot(A1, B)
print('\n', X)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
det = 59.999999999999986

 [-9.2         0.9         6.46666667]


### 6.2

In [41]:
A = np.array([[1, 2, -1], 
              [3, -4, 0], 
              [8, -5, 2], 
              [2, 0, -5], 
              [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])

pr = np.linalg.lstsq(A, B)[0]
print(pr)

[ 1.13919353 -0.90498444 -0.9009803 ]


In [42]:
print(np.dot(A, pr))

[ 0.23020495  7.03751834 11.83650981  6.78328855 15.21805313]


### 6.3 Сколько решений имеет линейная система